stages:
  - update-manifests

update-manifests:
  stage: udpate-manifests
  image: mikefarah/yq
  script: 
    - echo "Update ${SERVICE_NAME} image tag to ${NEW_TAG} in ${UPSTREAM_ENVIRONMENT_NAME}"
     # Update the image tag in deployment.yaml
    - yq -i "(.images[] | select(.name == \"$SERVICE_NAME\") | .newTag) = \"$NEW_TAG\"" overlays/dev/kustomization.yaml

    
    # Commit the changes back to the manifest repository
    - git config --global user.email "ci-bot@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git commit -am "Update image to $NEW_TAG"
    - git push origin main
  rules:
    # Run this downstream pipeline only if triggered by upstream pipeline.
    - if: $CI_PIPELINE_SOURCE == "pipeline"

