stages:
  - update-manifests

update-manifests:
  stage: update-manifests
  before_script:
    - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
    - chmod +x /usr/local/bin/yq
  script:
    # Commit the changes back to the manifest repository
    - git config --global user.email "ci-bot@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git checkout main
    - TARGET_ENV=$(yq '.labels[0].pairs.environment' overlays/dev/kustomization.yaml)
    - echo "Update $TARGET_ENV image tag to $NEW_TAG in $SERVICE_NAME"
     # Update the image tag in kustomization.yaml
    - yq -i "(.images[] | select(.name == \"$SERVICE_NAME\") | .newTag) = \"$NEW_TAG\"" overlays/dev/kustomization.yaml
    - git commit -am "Update image to $NEW_TAG"
    - git push -o ci.skip "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@gitlab.com/ranjitha-projects/spring-petclinic-gitops.git"
  rules:
    # Run this downstream pipeline only if triggered by upstream pipeline.
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: always

